### ISSUE TITLE
Add some basic CI

### ISSUE THREAD

**Issue by axelson** [hui-ad/institute#13]
Probably a free-for-open source CI should be fine. How about travis since it's easy to get started with?

**Comment by mudphone** [comment]
I'm open to anything you like!

**Comment by axelson** [comment]
@mudphone can you see if there's a pending request at either:
https://github.com/organizations/hui-ad/settings/installations
or
https://github.com/organizations/hui-ad/settings/installations

Re-opening until travis is actually running on commits

**Comment by mudphone** [comment]
👍 sorry for closing that
Don't currently see any pending requests. Are you not able to see that page? If not, maybe I can change some settings?

Also just found this for Gigaglixir: https://gigalixir.readthedocs.io/en/latest/main.html#how-to-set-up-continuous-integration-ci-cd

**Comment by axelson** [comment]
Yeah I don't have the right organizational permissions to see that page.

**Comment by mudphone** [comment]
Okay, interesting. I made you an *admin* on this repo. Since that's the highest setting, I hope that works. If not, let me know and we can try something else. Thanks! Happy 4th!!! 🎆 🎉 🎉 🎉 🎉

**Comment by axelson** [comment]
@mudphone Okay I think this is the correct link for the pending requests:

https://github.com/organizations/ElixirHawaii/settings/oauth_application_policy

Or do you see the ability to give travis-ci.org access to the repository/org here:

https://github.com/settings/connections/applications/f244293c729d5066cf27

I believe you once you enable it you have the option to either give it access to all the repositories in the organization or individual ones. Alternatively you could give me admin access to the organization.

**Comment by mudphone** [comment]
That second link was it. I granted CircleCI access to the HUI-AD org.

**Comment by mudphone** [comment]
Okay, you're also have the `owner` role on the HUI-AD org.

**Comment by axelson** [comment]
Wasn't trying to add CircleCI ;) (was trying travis). I got it set up now though, thanks for the permissions! Just need the build to actually complete, haha

**Comment by mudphone** [comment]
Whoops! Okay, I reread that page and it was allowing CircleCI access to my GitHub account. That was an old request from an old project.
